#ifndef FREERTOS_APP_SIZING_H
#define FREERTOS_APP_SIZING_H

#define APP_TASK_STACK_DEPTH_RACK_BUZZER        (configMINIMAL_STACK_SIZE * 1)
#define APP_TASK_STACK_DEPTH_RACK_OLED          (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_RACK_MQTT          (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_RACK_DOOR_MQTT     ((configMINIMAL_STACK_SIZE * 3) / 2)
#define APP_TASK_STACK_DEPTH_RACK_POLLING       (configMINIMAL_STACK_SIZE * 1)
#define APP_TASK_STACK_DEPTH_RACK_GPS           (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_RACK_GPS_MQTT      (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_RACK_TMP_HUM       (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_RACK_TMP_MQTT      (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_RACK_SIGN_ON       (configMINIMAL_STACK_SIZE * 1)
#define APP_TASK_STACK_DEPTH_RACK_NETWORK_POLL  (configMINIMAL_STACK_SIZE * 1)
#define APP_TASK_STACK_DEPTH_RACK_TILT          (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_RTOS_MONITOR       (configMINIMAL_STACK_SIZE * 3)
#define APP_TASK_STACK_DEPTH_COMMAND            (configMINIMAL_STACK_SIZE * 3)
#define APP_TASK_STACK_DEPTH_KBD_POLL           (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_MENU_OLED          (configMINIMAL_STACK_SIZE * 2)
#define APP_TASK_STACK_DEPTH_WATCHDOG           (configMINIMAL_STACK_SIZE * 1)

#define APP_FREERTOS_DYNAMIC_TASKS_STACK_DEPTH_SUM \
    ( ( APP_TASK_STACK_DEPTH_RTOS_MONITOR ) + \
      ( APP_TASK_STACK_DEPTH_RACK_NETWORK_POLL ) + \
      ( APP_TASK_STACK_DEPTH_COMMAND ) + \
      ( APP_TASK_STACK_DEPTH_RACK_TILT ) + \
      ( APP_TASK_STACK_DEPTH_RACK_TMP_HUM ) + \
      ( APP_TASK_STACK_DEPTH_RACK_GPS ) + \
      ( APP_TASK_STACK_DEPTH_KBD_POLL ) + \
      ( APP_TASK_STACK_DEPTH_MENU_OLED ) + \
      ( APP_TASK_STACK_DEPTH_RACK_OLED ) + \
      ( APP_TASK_STACK_DEPTH_RACK_DOOR_MQTT ) + \
      ( APP_TASK_STACK_DEPTH_RACK_GPS_MQTT ) + \
      ( APP_TASK_STACK_DEPTH_RACK_MQTT ) + \
      ( APP_TASK_STACK_DEPTH_RACK_TMP_MQTT ) + \
      ( APP_TASK_STACK_DEPTH_RACK_MQTT ) + \
      ( APP_TASK_STACK_DEPTH_WATCHDOG ) + \
      ( APP_TASK_STACK_DEPTH_RACK_BUZZER ) )

#define APP_FREERTOS_DYNAMIC_TASK_COUNT (16u)

#ifndef APP_FREERTOS_ESTIMATED_TCB_BYTES_PER_TASK
#define APP_FREERTOS_ESTIMATED_TCB_BYTES_PER_TASK (512u)
#endif

#ifndef APP_FREERTOS_OBJECTS_RESERVE_BYTES
#define APP_FREERTOS_OBJECTS_RESERVE_BYTES (8u * 1024u)
#endif

#ifndef APP_FREERTOS_RUNTIME_RESERVE_BYTES
#if ( ENABLE_RTOS_ANALYSIS == 1 )
#define APP_FREERTOS_RUNTIME_RESERVE_BYTES (32u * 1024u)
#else
#define APP_FREERTOS_RUNTIME_RESERVE_BYTES (64u * 1024u)
#endif
#endif

#ifndef APP_FREERTOS_STACK_WORD_BYTES
#define APP_FREERTOS_STACK_WORD_BYTES (4u)
#endif

#define APP_FREERTOS_STACK_BYTES \
    ( (unsigned long)(APP_FREERTOS_DYNAMIC_TASKS_STACK_DEPTH_SUM) * (unsigned long)(APP_FREERTOS_STACK_WORD_BYTES) )

#define APP_FREERTOS_TCB_BYTES \
    ( (unsigned long)(APP_FREERTOS_DYNAMIC_TASK_COUNT) * (unsigned long)(APP_FREERTOS_ESTIMATED_TCB_BYTES_PER_TASK) )

#define APP_FREERTOS_HEAP_BASE_BYTES \
    ( (unsigned long)(APP_FREERTOS_STACK_BYTES) + (unsigned long)(APP_FREERTOS_TCB_BYTES) + \
      (unsigned long)(APP_FREERTOS_OBJECTS_RESERVE_BYTES) + \
      (unsigned long)(APP_FREERTOS_RUNTIME_RESERVE_BYTES) )

#define APP_FREERTOS_HEAP_WITH_30_PERCENT_HEADROOM_BYTES \
    ( (unsigned long)(( APP_FREERTOS_HEAP_BASE_BYTES * 130u ) / 100u) )

#define APP_FREERTOS_HEAP_ALIGN8(x) ( ( (unsigned long)(x) + 7u ) & ~( (unsigned long)7u ) )

#define APP_FREERTOS_TOTAL_HEAP_BYTES \
    ( APP_FREERTOS_HEAP_ALIGN8(APP_FREERTOS_HEAP_WITH_30_PERCENT_HEADROOM_BYTES) )

#endif /* FREERTOS_APP_SIZING_H */
