#ifndef KEYBOARD_PARAMETERS_H
#define KEYBOARD_PARAMETERS_H

#define KEYBOARD_ROW2_PIN 18
#define KEYBOARD_ROW1_PIN 19
#define KEYBOARD_ROW0_PIN 20
#define KEYBOARD_ROW3_PIN 17

#define KEYBOARD_COL3_PIN 4
#define KEYBOARD_COL2_PIN 8
#define KEYBOARD_COL1_PIN 9
#define KEYBOARD_COL0_PIN 16

#endif // KEYBOARD_PARAMETERS_H